FROM nginx:latest
COPY ./config/default.conf /etc/nginx/conf.d/defaut.conf
COPY ./config/certs/server.crt /etc/ssl/private/server/server.crt
COPY ./config/certs/server.key /etc/ssl/private/server/server.key