upstream appserver {
    zone upstreams 64K;
    server wsserver:3000 max_fails=2 fail_timeout=10s;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    server_tokens off;
    proxy_set_header Host $host:$proxy_port;
    listen 443 ssl;

    ssl_certificate /etc/ssl/private/server/server.crt;
    ssl_certificate_key /etc/ssl/private/server/server.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    client_max_body_size 64M;
    location / {
        proxy_next_upstream error timeout http_500;
        proxy_pass http://appserver/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
